### ISSUE TITLE
We can't add a new rule

### ISSUE THREAD

**Issue by LeaMiage** [TheoChevalier/typolib#163]
AJAX doesn't seem to work.

**Comment by TheoChevalier** [comment]
Works for me on http://typolib.theochevalier.fr/edit
I think it has the latest changes, I'll try to push to prod

**Comment by LeaMiage** [comment]
Works for "replace_with" but not with "quotation_mark"

**Comment by TheoChevalier** [comment]
D'oh. Nice catch! Will fix tomorrow :)
