### ISSUE TITLE
Adding rule type to skip variables

### ISSUE THREAD

**Issue by TheoChevalier** [TheoChevalier/typolib#64]

**Comment by thibautRevilliod** [comment]
I'm using tags : <var> and </var> to mark variables in text. Then, when we parse the text, we ignore all our custom tags.

**Comment by TheoChevalier** [comment]
Not sure if you've seen this, but if that helps, Transvision is also marking strings to insert html: https://github.com/TheoChevalier/transvision/blob/master/app/classes/Transvision/Utils.php#L78

**Comment by thibautRevilliod** [comment]
Looks good but it seems there are some issues with the '←→' characters

**Comment by TheoChevalier** [comment]
hm, then something is probably fucked up on our side :/

**Comment by TheoChevalier** [comment]
We should be using UTF-8 everywhere

**Comment by thibautRevilliod** [comment]
Allow user to input several variables separated with spaces
